### ISSUE TITLE
2 issues; 1) Invalid value for '--gainref' and 2)MDOC file designation

### ISSUE THREAD

**Issue by rnwokonko** [tomotools/tomotools#13]
Hey, I think this tool will be very helpful for my project but I am running into 2 seemingly small issues that are preventing me from running the tomotools batch-prepare-tiltseries --splitsum --gainref protocol.

First, I am getting an error that it cannot find the gainref file - "Error: Invalid value for '--gainref':". I've tried a number of ways to get it to recognize the file, but have had no success. The file is currently located in the same directory as the input tif frame files.

The second quest that I am have is about the MDOC files. Currently, I only have 1 MDOC file per batch of tif frames. Do I need to generate an MDOC for each tilt?

Would appreciate any insight that can help me move past these errors. 

Best,
Robert

**Comment by rnwokonko** [comment]
@bwmr Apologies, I put this project down for a while and am finally picking it back up. My first comment was misguided. It seems like my data does not fulfill the 'prerequisites'. During my collection I do not save my data as even/odd frames, instead I was hoping to split them after the fact using either motioncorr or imod. I initially thought this tool would help with that, but it appears that is incorrect.

**Comment by bwmr** [comment]
Hi @rnwokonko,
If you have the frames, you can indeed create the EVN/ODD stacks after the fact with MotionCor2 - just run `tomotools batch-prepare-tiltseries` with the `--splitsum` tag. 
Hope this helps,
Benedikt

**Comment by bwmr** [comment]
closed due to inactivity
