### ISSUE TITLE
Wrong SubFramePath from aretomo2warp

### ISSUE THREAD

**Issue by MoritzWM** [tomotools/tomotools#17]
I tested the aretomo2warp function for the first time and found an issue. Everything worked as it should until I checked the tilt handedness in Warp, which gave me a correlation of 0.06 despite good CTF estimation.
The reason was in the SubFramePath fields in the MDOC file. They are all over the place. After fixing them manually all was fine.

The file as it was generated:
```
PixelSpacing = 2.671
Voltage = 300
Version = SerialEM Version 4.1.0beta 64-bit,  built Sep 27 2022  00:59:42
ImageFile = L02_ts_002.mrc
ImageSize = 5760 4092
DataMode = 3


[T =    SerialEM: Krios_K3_Heidelberg University                10-Jan-23  16:45:39]

[T =    Tilt axis angle = 80.2, binning = 1  spot = 7  camera = 0]

[ZValue = 0]
TiltAngle = -52.0011
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_00.mrc

[ZValue = 1]
TiltAngle = -49.0025
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_18.mrc

[ZValue = 2]
TiltAngle = -46.0024
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_15.mrc

[ZValue = 3]
TiltAngle = -43.0017
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_16.mrc

[ZValue = 4]
TiltAngle = -40.0036
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_07.mrc

[ZValue = 5]
TiltAngle = -37.003
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_05.mrc

[ZValue = 6]
TiltAngle = -34.0028
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_19.mrc

[ZValue = 7]
TiltAngle = -31.0032
SubFramePath = X:\WarpDir\L01_ts_002_ali_sec_38.mrc
...
```

**Comment by MoritzWM** [comment]
After this, the correlation is 0.99 but the reconstruction is still terrible... But maybe that's just Warp

**Comment by MoritzWM** [comment]
Confirmed that the terrible reconstruction quality is just warp

**Comment by bwmr** [comment]
I could not replicate the bug. For me, the SubFramePaths in the mdoc follow the same order as the stack (as it should). Theoretically, the function just gets the list of all exported files in alphabetical order and then puts them into the mdoc. Can you run the function line-by-line to test where the error occurs or somehow send me this tomogram? 
I am using AreTomo 1.3.3, imod 4.12.35 and python 3.8.16.
