### ISSUE TITLE
is git-lfs essential?

### ISSUE THREAD

**Issue by McHaillet** [tomotools/tomotools#22]
Hi!

Thanks for the cool work on this repo. I am especially interested that you now also provide options for ctf3d in version 0.3.1 , as I now always have to script a lot around novaCTF. 

I was wondering how important it is to have git-lfs for installation? I assume its for test-files in the repository, perhaps for the unittests they can be much smaller (or binned). I thought it might make it easier to install.

Best wishes,
Marten

**Comment by McHaillet** [comment]
Hi Benedikt,

Indeed, I noticed its not exposed yet, any idea when it will become available?

I ran this command, as per the installation instructions:
```
pip install "tomotools[cryocare] @ git+https://github.com/tomotools/tomotools.git"
```
This is the output that I got:
```
Collecting tomotools@ git+https://github.com/tomotools/tomotools.git (from tomotools[cryocare]@ git+https://github.com/tomotools/tomotools.git)
  Cloning https://github.com/tomotools/tomotools.git to /tmp/pip-install-zpznt4ss/tomotools_759f26800b9646f68f0819e3daba2e23
  Running command git clone --filter=blob:none --quiet https://github.com/tomotools/tomotools.git /tmp/pip-install-zpznt4ss/tomotools_759f26800b9646f68f0819e3daba2e23
  git-lfs filter-process: git-lfs: command not found
  fatal: the remote end hung up unexpectedly
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/tomotools/tomotools.git /tmp/pip-install-zpznt4ss/tomotools_759f26800b9646f68f0819e3daba2e23 did not run successfully.
  \u2502 exit code: 128
  \u2570\u2500> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/tomotools/tomotools.git /tmp/pip-install-zpznt4ss/tomotools_759f26800b9646f68f0819e3daba2e23 did not run successfully.
\u2502 exit code: 128
\u2570\u2500> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I managed to install it after adding git-lfs.

**Comment by bwmr** [comment]
Hi Marten,

Thanks for pointing out the git-lfs error, I will try to check out possible workarounds! Clearly, git-lfs should only be required for the development workflow and not for the general install. 

Regarding `ctf3d` I do not yet have a fixed timeline, but I can try to do it some time this month - or if it's urgent, feel free to add it and submit a PR :) 

Best,
Benedikt

**Comment by bwmr** [comment]
Hi Marten, 

I have created a workaround in the branch [fix-install-nogitlfs](https://github.com/tomotools/tomotools/tree/fix-install-nogitlfs). Could you test whether it works for you now? Unfortunately, I cannot uninstall git-lfs on my workstation...
If it works, I will merge into main. 

Best,
Benedikt

**Comment by McHaillet** [comment]
Thanks a lot for the quick update! Will also give it a try on Monday :)

**Comment by McHaillet** [comment]
Hi Benedikt! It works nicely for me, thanks for the fix :)
