### ISSUE TITLE
exposuredose 

### ISSUE THREAD

**Issue by McHaillet** [tomotools/tomotools#27]
Hi Benedikt,

For the `--exposure-dose` option in the tilt-series preparation, I had expected it would overwrite the dose in the new .mdoc that is created in the output directory. The current dataset that I am processing has some weird values here (such as 0.0), so it would be nice to manually force it with a value to apply dose filtering. I thought it might be a bug

Best!

**Comment by bwmr** [comment]
Hi Marten, 
You're right, that's what the flag is supposed to do, but also for me it doesn't seem to work. I'll try to check it out in the course of the week. 
Cheers

**Comment by bwmr** [comment]
Alright, fixed in newest commit.

**Comment by McHaillet** [comment]
Very nice, thanks!
