### ISSUE TITLE
issue with tomo positioning via IMOD

### ISSUE THREAD

**Issue by McHaillet** [tomotools/tomotools#29]
IMOD's findsection produces the following: 
```
findsection -tomo tomo.mrc -pitch tomo.mod -scales 2 -size 16,1,16 -samples 5 -block 48
               center   center SDs      edge     edge SDs      distinct-
scale  binning  mean   median  MADN     mean   median  MADN      ness
ERROR: findsection - For all scalings, too few boxes in center sample where boundaries of section could be detected
```
It could also be the tomo I am testing as I am not familiar with running this IMOD command. The dimensions are quite standard though 512x512x250

_Originally posted by @McHaillet in https://github.com/tomotools/tomotools/issues/26#issuecomment-1938668962_

**Comment by McHaillet** [comment]
The tomogram dimension I mentioned are with 8x binning already, so that should be quite standard.

**Comment by bwmr** [comment]
Alright, that makes more sense in terms of dimensions. So you're reconstructing super-resolution stacks? 

FWIW, the automatic positioning often fails for me, but it should be caught by the error handling [here](https://github.com/tomotools/tomotools/blob/b49ae4c51fb05bff3fd66c5ff1ffc4758773b915/tomotools/commands/preprocessing_reconstruction.py#L539-L541): 

```
if fs.returncode != 0:  
                print(  
                    f'{tiltseries.path}: findsection failed, using default values.')
```

**Comment by McHaillet** [comment]
Indeed, it is caught correctly by error handling.
I guess then its a general issue that its not so reliable. Any idea if it can be improved by playing with the input parameters?

**Comment by bwmr** [comment]
tbh I don't really use it so much - but @MoritzWM does, maybe he has some input :)

**Comment by MoritzWM** [comment]
Hey, sorry for not being very responsive right now.

I didn't figure out the parameters myself, they are from the etomo source code. 
If you do a reconstruction with your tomogram in etomo and perform automatic positioning, does it work? Maybe etomo has some more sophisticated error handling and tries more parameters,.

**Comment by bwmr** [comment]
> Indeed, it is caught correctly by error handling. I guess then its a general issue that its not so reliable. Any idea if it can be improved by playing with the input parameters?

Just to confirm: the error handling catches this and it doesn't lead to a failed `tomotools reconstruct` run, but just continues normally, right?

**Comment by McHaillet** [comment]
> > Indeed, it is caught correctly by error handling. I guess then its a general issue that its not so reliable. Any idea if it can be improved by playing with the input parameters?
> 
> Just to confirm: the error handling catches this and it doesn't lead to a failed `tomotools reconstruct` run, but just continues normally, right?

Yep it finishes correctly
