### ISSUE TITLE
batch-prepare-tiltseries empty value

### ISSUE THREAD

**Issue by alicethurston** [tomotools/tomotools#38]
I get this error:

Parsing error, invalid line: "ChannelName ="

Thanks :)

**Comment by bwmr** [comment]
https://github.com/tomotools/tomotools/blob/cb21eebc1c38c44e6ac83b5a6f95aabff605e420/tomotools/utils/mdocfile.py#L92C1-L96C68

error comes from stupid Tomo5 putting empty things in mdoc. Maybe just add a `continue` statement in the `except` block? (https://stackoverflow.com/a/19523054)

**Comment by bwmr** [comment]
turns out crash wasn't caused by this at all
